version: '3.9'
services:
    php-apache:
      container_name: php_obj
      build: .
      restart: always
      depends_on:
        - mariadb
      ports:
        - 8080:80
      volumes:
        - ./Teorico/progobjetos:/var/www/html
      networks:
        - network

    mariadb:
      container_name: mariadb_obj
      image: mariadb:10.6
      restart: always
      ports:
        - 3306:3306
      volumes:
        - mariadb:/var/lib/mysql
      environment:
        MYSQL_DATABASE: database
        MYSQL_USER: admin
        MYSQL_PASSWORD: admin
        MYSQL_ROOT_PASSWORD: root
      networks:
        - network

networks:
  network:
    driver: bridge

volumes:
  mariadb: